### ISSUE TITLE
Move `unlockerd` inside `tdexd` and add `UNLOCK_PASSWORD_FILE` config ENV VAR option to make unlocker feature inside `tdexd`

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-daemon#557]
TODO:

- [x] move unlocker functionalities inside `tdexd`
- [x] add new ENV VAR
- [ ] change tdex-box docker-compose and mount the volume with pwd.txt inside according to new ENV VAR
- [ ] change documentation in the Dev Portal
- [ ] change documentation in the README

**Comment by tiero** [comment]
To prevent this, should maybe the `tdexd` "pulls" the password IN instead of being a separated service?

LND does the same apparently, we can have an ENV VAR to specify where the password is.

https://github.com/lightningnetwork/lnd/blob/master/docs/wallet.md#auto-unlocking-a-wallet

TODO:

- [ ] move unlocker functionalities inside `tdexd`
- [ ] add new ENV VAR
- [ ] change tdex-box docker-compose and mount the volume with pwd.txt inside according to new ENV VAR
- [ ] change documentation in the Dev Portal

**Comment by tiero** [comment]
First thing is to try to replicate the issue with docker compose

1. Create a compose like the following
```yml
version: "3.7"

services:
  # TDEX daemon connected to Blockstream.info explorer
  tdexd:
    container_name: "tdexd"
    image: ghcr.io/tdex-network/tdexd:latest
    restart: unless-stopped
    environment:
      - TDEX_LOG_LEVEL=5
      - TDEX_NETWORK=testnet
      - TDEX_BASE_ASSET=144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49
      - TDEX_NATIVE_ASSET=144c654344aa716d6f3abcc1ca90e5641e4e2a7f633bc09fe3baf64585819a49
      - TDEX_EXPLORER_ENDPOINT=https://blockstream.info/liquidtestnet/api
    ports:
      - "9945:9945"
      - "9000:9000"
    #### Unlocker with file ####
    # Uncomment to override default command and start tdexd and unlockerd.
    # You need to uncomment also the volume down that mount the path used here.
    command: /bin/bash -c "(sleep 1 && unlockerd --password_path=/pwd.txt --interval=10 >& /dev/null &) && /tdexd-linux"

    volumes:
      - ./tdexd:/home/user/.tdex-daemon
      - ${PWD}/pwd.txt:/pwd.txt
```

2. Run it with `docker-compose up`

3. initialize with seed and password and put it in the pwd.txt file in local path

4. check status with `docker exec -it tdexd tdex status`

5. Restart the Docker engine (or Docker Desktop if on Mac)

Is it unlocker working?
